### ISSUE TITLE
SQL logs appear even in :info level?

### ISSUE THREAD

**Issue by jgeiger** [iMacTia/lograge-sql#12]
I've just replaced logstasher with the lograge/lograge-sql combo and it seems that if I enable lograge-sql, it will show the sql logging when 

config.log_level = :info

is set for the environment, which doesn't seem correct.

If I disable the gem, the lograge output is missing the SQL. If I set the level back to :debug, the lograge output has the poorly formatted SQL.

**Comment by iMacTia** [comment]
Hi @jgeiger and thanks for choosing `lograge-sql` 🙌

I can totally see your point and what you're trying to do, however this gem doesn't really provide "logging" functionality, but instead takes care of silencing the default SQL logs and add them instead to the `lograge` payload.
For that reason, I didn't really think about the logging level at all, assuming it will just be the same as the rest of the `lograge` payload.
SQL queries are simply always added, as you can see fromhttps://github.com/iMacTia/lograge-sql/blob/master/lib/lograge/sql/extension.rb#L9

For this reason, I'm not entirely sure how to integrate the standard logging into the equation, but I'm open to suggestions.

One thing you can do right now, is taking advantage of the formatter customisation:

```
# config/initializers/lograge.rb
Rails.application.configure do
  # Swallows the sql_queries output if condition satisfied
  config.lograge_sql.formatter = Proc.new { |_| '[REMOVED]' } if condition_to_disable_sql_queries
end
```

This way you can remove sql queries based on any condition, like and `ENV` variable or the logger level.
Let me know if that works for you, otherwise I'm still open to suggestions

**Comment by jgeiger** [comment]
>> silencing the default SQL logs and add them instead to the lograge payload.

I think that's the issue. In **:info** there shouldn't be any SQL logs, but they show up only when this gem is enabled.

**Comment by iMacTia** [comment]
Yeah, that was a bit oversimplifying it though 😅.
What the gem does is listening to query events and collecting them, then adding them to the lograge payload. There’s no direct involvement with any logger if you look at the code, hence why although your request sounds logical, it’s not that trivial.

I hope that explains the problem a bit better, and why it isn’t so obvious that the sql queries presence in the lograge logger is dictated by the log level.

**Comment by mbarany** [comment]
I also agree it was a bit odd at first to always see the queries. An alternative approach here is to skip the code initialization all together if your log_level.

```ruby
#config/initializers/lograge.rb

# lograge config here

return unless Rails.config.log_level == :debug

require 'lograge/sql/extension'

# lograge-sql config here
```

**Comment by iMacTia** [comment]
Closing this old issue as effectively "won't do".
As it was explained above, `lograge-sql` doesn't interact with a logger directly, but it simply communicates with `lograge`.
If anyone wants to skip SQL logging based on the log_level, you can do what @mbarany suggested above ☝️
