### ISSUE TITLE
Query Runtime is Summed Twice

### ISSUE THREAD

**Issue by hosamaly** [iMacTia/lograge-sql#37]
When `config.lograge_sql.keep_default_active_record_log = true`, query runtime gets summed twice: once in `ActiveRecord::LogSubscriber` and again in `Lograge::ActiveRecordLogSubscriber`.

**Comment by iMacTia** [comment]
That's a great catch @hosamaly, I suspect the culprit is [this line here](https://github.com/iMacTia/lograge-sql/blob/master/lib/lograge/active_record_log_subscriber.rb#L9).
The solution would be to add a condition to that so that we only sum if `config.lograge_sql.keep_default_active_record_log` is disabled.

Shouldn't be too hard of a change, would you like to give it a try?

**Comment by hosamaly** [comment]
I would've normally done that but I've got a lot on my plate at the moment. I could get back to it in a week but I hope that it will be fixed by then :)
