### ISSUE TITLE
Option to separate SQL logs from request log lines

### ISSUE THREAD

**Issue by itay-grudev** [iMacTia/lograge-sql#43]
A very beneficial option would be to separate SQL logs on a separate line and specify different log level.

In my specific case I'd like to log SQL queries under DEBUG level, while request logs under `INFO` level.

Is that feasible given the current code base?

**Comment by iMacTia** [comment]
Hi @itay-grudev, this is not currently possible because this gem is an extension of Lograge and does not directly manage the write-to-output.

One way to achieve a similar result is by conditionally enabling the extension based on the logger level.
If, for example, you only want to collect and log SQL queries while debugging, you could achieve this with the following:

```ruby
# Then in the lograge initializer
require 'lograge/sql/extension' if Rails.logger.level == Logger::DEBUG
```

This way, although they'd still appear inside the request logs, they would only be there if and only if you're logging at DEBUG level. Even the (small) collection of SQL queries would be disabled unless your debugging.

Would this be a viable alternative for you?

**Comment by itay-grudev** [comment]
Not ideal, because I wanted to separate them at the logging middleware (FluentD), but I can work with that. Thank you very much for the quick response.
