### ISSUE TITLE
Rails 7.1 deprecation warnings

### ISSUE THREAD

**Issue by alex-tan** [iMacTia/lograge-sql#54]
Just upgraded to Ralis 7.1 on a project and noticed these deprecation warnings:

Beginning of trace:

```
DEPRECATION WARNING: 
ActiveRecord::LogSubscriber.runtime= is deprecated and will be removed in Rails 7.2.  (called from load at [APP]/vendor/bundle/ruby/3.2.0/bin/rspec:25)
[APP]/vendor/bundle/ruby/3.2.0/gems/lograge-sql-2.3.0/lib/lograge/active_record_log_subscriber.rb:24:in `increase_runtime_duration'
[APP]/vendor/bundle/ruby/3.2.0/gems/lograge-sql-2.3.0/lib/lograge/active_record_log_subscriber.rb:9:in `sql'
```

**Comment by iMacTia** [comment]
Thank you for reporting this @alex-tan 🙏 !
This warning seems to be due to [this change](https://github.com/rails/rails/commit/f56b4187be56304857b57ec7159a8e2dc2b91dea) and is indeed something we'll need to fix before we can add compatibility with Rails 7.2.

I'll need some more time to look into this though, so if in the meantime someone wants to take a stab at fixing it, I hope the PR above will contain enough context to get started 😄

**Comment by bolah2009** [comment]
@iMacTia I created a PR for this issue in https://github.com/iMacTia/lograge-sql/pull/55
